name: unittest
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: unittest
        run: go test ./...
